### PR TITLE
Update runtime to 44

### PR DESCRIPTION
**Pull request by farribeiro**

### CODE REVIEW

**Comment by guihkx** [comment]
I will merge this eventually, but right now it seems like there's no app out there currently using this version of the runtime, so I'll probably wait for v44 to surpass v43 in usage.

Apps using v43:

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/43 flathub | wc -l
339
```

Apps using v44:

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/44 flathub | wc -l
0
```

**Comment by farribeiro** [comment]
The 44  runtime was released today and the announce may be tomorrow,

PS1:  no one changed the runtime yet, except me

PS2: The surpass may not happens. the update runtimes is manually and also may it has a lot of packages unmaintained

**Comment by guihkx** [comment]
>The 44 runtime was released today and the announce may be tomorrow,

Oh, I see.

>PS2: The surpass may not happens. the update runtimes is manually and also has a lot of packages unmaintained

If we look at previous versions of the runtime, I think it's safe to assume the mass move to v44 will eventually happen as well:

v42:

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/42 flathub | wc -l
230
```

v41:

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/41 flathub | wc -l
35
```

v40:

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/40 flathub | wc -l
20
```

The only reason I don't want to merge this right now is because there's no actual reason to. We actually only use the GNOME runtime to make links inside the program open properly on the web browser, and v43 (which is the most used runtime at the moment) takes care of that. 😄

**Comment by farribeiro** [comment]
I think is good to merge now

**Comment by guihkx** [comment]
Not yet:

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/43 flathub | wc -l
241
```

```
$ flatpak remote-ls --app-runtime=org.gnome.Platform/x86_64/44 flathub | wc -l
178
```

The version of the GNOME runtime used is not *that* important for this app, therefore I think we should stick with the most popular one.

**Pull request merged**
